# Generated by Django 5.1.2 on 2024-10-12 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=100)),
                ("asn", models.CharField(blank=True, max_length=100, null=True)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("online", models.BooleanField(blank=True, null=True)),
                ("item_name", models.CharField(blank=True, max_length=100, null=True)),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("brand_name", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("productDetail", models.TextField(blank=True, null=True)),
                ("price", models.FloatField(blank=True, null=True)),
                ("picture_main", models.TextField(blank=True, null=True)),
                ("quantity_in_stock", models.IntegerField(blank=True, null=True)),
                ("quantity_on_order", models.IntegerField(blank=True, null=True)),
                ("color_option", models.IntegerField(blank=True, null=True)),
                ("pickup_option", models.IntegerField(blank=True, null=True)),
                ("shape_option", models.IntegerField(blank=True, null=True)),
                ("created_at", models.TextField(blank=True, null=True)),
                ("image_urls", models.TextField(blank=True, null=True)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("glasgow_quantity", models.IntegerField(blank=True, null=True)),
                ("edinburgh_quantity", models.IntegerField(blank=True, null=True)),
                ("newcastle_quantity", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("band", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "products",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uses",
                        to="music.gear",
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artists",
                        to="music.genre",
                    ),
                ),
            ],
        ),
    ]
