# Generated by Django 5.1.2 on 2024-10-12 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('asn', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('online', models.BooleanField()),
                ('item_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('productDetail', models.TextField()),
                ('price', models.FloatField()),
                ('picture_main', models.TextField()),
                ('quantity_in_stock', models.IntegerField()),
                ('quantity_on_order', models.IntegerField()),
                ('color_option', models.IntegerField()),
                ('pickup_option', models.IntegerField()),
                ('shape_option', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('image_urls', models.TextField()),
                ('rating', models.FloatField()),
                ('glasgow_quantity', models.IntegerField()),
                ('edinburgh_quantity', models.IntegerField()),
                ('newcastle_quantity', models.IntegerField()),
                ('artists', models.ManyToManyField(related_name='gears', to='music.artist')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artists', to='music.genre'),
        ),
    ]
